include:
  - project: 'antwerpen/across/across-development'
    file:
      - '/gitlab-ci/docker.gitlab-ci.yml'
      - '/gitlab-ci/common.gitlab-ci.yml'
      - '/gitlab-ci/unit-tests.gitlab-ci.yml'
      - '/gitlab-ci/unit-tests-docker.gitlab-ci.yml'
      - '/gitlab-ci/integration-tests-docker.gitlab-ci.yml'
      - '/gitlab-ci/deploy.gitlab-ci.yml'

variables:
  ACROSS_FRAMEWORK_VERSION: 5.4-SNAPSHOT
  REVISION: 2.4-SNAPSHOT
